In [1]:
from __future__ import division, print_function
import os
import numpy as np
import random as rnd
import pandas as pd
import random
from sklearn.decomposition import PCA

In [2]:
# arr_train = np.load("../haar_train_full.npy")
# arr_test = np.load("../haar_test_full.npy")

df_X = pd.read_csv("../Haar_Features/X_df.csv") 
df_y = pd.read_csv("../Haar_Features/y_df.csv") 
df_X = (df_X - df_X.mean()) / df_X.std()

In [3]:
X = np.array(df_X)
y = np.array(df_y)
y = np.squeeze(y)


# train_df = pd.DataFrame(arr_train)
# test_df = pd.DataFrame(arr_test)
# test_df.head()

# train_feature = train_df.iloc[:, :-1]
# test_feature = test_df.iloc[:, :-1]

# WholeDf = pd.concat([train_feature, test_feature])

In [4]:
X.shape

(12000, 200)

In [5]:
# def train_test_split(df, test_size):
    
#     if isinstance(test_size, float):
#         test_size = round(test_size * len(df))

#     index_list = df.index.tolist()
#     test_indices = random.sample(population=index_list, k=test_size)

#     test_df = df.loc[test_indices]
#     train_df = df.drop(test_indices)
    
#     return train_df, test_df

In [6]:
# pca = PCA(n_components=50)
# principalComponents = pca.fit_transform(WholeDf)
# principalDf = pd.DataFrame(data = principalComponents)

In [7]:
# train_features = principalDf.iloc[0:12000]
# test_features = principalDf.iloc[60000:]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
uni_code = {}

In [9]:
count = 0
while (count!= 10):
    uni_code[count] = np.random.randint(2, size=50)
    count = count+1

In [10]:
y_test_mat = [None] * len(y_test)
y_train_mat = [None] * len(y_train)

In [11]:
# random.seed(3)
# train_df, test_df = train_test_split(df, 0.20)
for i in range(len(y_test)):
    y_test_mat[i] = uni_code.get(int(y_test[i]))
    
for i in range(len(y_train)):
    y_train_mat[i] = uni_code.get(int(y_train[i]))

In [12]:
y_test_df = pd.DataFrame.from_records(y_test_mat)
X_test_df = pd.DataFrame.from_records(X_test)

y_train_df = pd.DataFrame.from_records(y_train_mat)
X_train_df = pd.DataFrame.from_records(X_train)

In [13]:
y_train_df = y_train_df.replace(0, -1)
y_test_df = y_test_df.replace(0, -1)
y_train_df.head()

0   1   2   3   4   5   6   7   8   9  ...  40  41  42  43  44  45  46  47  \
0   1   1   1  -1   1   1   1   1   1  -1 ...  -1  -1  -1  -1   1  -1  -1   1   
1   1  -1   1   1   1   1   1   1   1  -1 ...  -1   1   1  -1  -1  -1   1   1   
2   1   1   1   1   1  -1  -1  -1  -1   1 ...  -1   1   1   1   1  -1  -1   1   
3   1   1   1  -1   1   1   1   1   1  -1 ...  -1  -1  -1  -1   1  -1  -1   1   
4   1  -1   1   1   1   1   1   1   1  -1 ...  -1   1   1  -1  -1  -1   1   1   

   48  49  
0   1   1  
1   1  -1  
2   1  -1  
3   1   1  
4   1  -1  

[5 rows x 50 columns]

In [14]:
y_train_mat

[array([1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 1, 1]),
 array([1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
        0, 0, 1, 1, 1, 0]),
 array([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
        1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
        1, 0, 0, 1, 1, 0]),
 array([1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 1, 1]),
 array([1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
        0, 0, 1, 1, 1, 0]),
 array([0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,

In [15]:
y_train[0]

9

In [16]:
max_iter=200
kernel_type='linear'
C=0.01
epsilon=0.001

In [17]:
def fit(X, y):
    # Initialization
    n, d = X.shape[0], X.shape[1]
    alpha = np.zeros((n))
    kernel = kernels[kernel_type]
    count = 0
    while True:
        count += 1
        alpha_prev = np.copy(alpha)
        for j in range(0, n):
            i = get_rnd_int(0, n-1, j) # Get random int i~=j
            x_i, x_j, y_i, y_j = X[i,:], X[j,:], y[i], y[j]
            k_ij = kernel(x_i, x_i) + kernel(x_j, x_j) - 2 * kernel(x_i, x_j)
            if k_ij == 0:
                continue
            alpha_prime_j, alpha_prime_i = alpha[j], alpha[i]
            (L, H) = compute_L_H(C, alpha_prime_j, alpha_prime_i, y_j, y_i)

            # Compute model parameters
            w = calc_w(alpha, y, X)
            b = calc_b(X, y, w)

            # Compute E_i, E_j
            E_i = prediction_error(x_i, y_i, w, b)
            E_j = prediction_error(x_j, y_j, w, b)

            # Set new alpha values
            alpha[j] = alpha_prime_j + float(y_j * (E_i - E_j))/k_ij
            alpha[j] = max(alpha[j], L)
            alpha[j] = min(alpha[j], H)

            alpha[i] = alpha_prime_i + y_i*y_j * (alpha_prime_j - alpha[j])

        # Check convergence
        diff = np.linalg.norm(alpha - alpha_prev)
        if diff < epsilon:
            break

        if count >= max_iter:
            print("Iteration number exceeded the max of %d iterations" % (max_iter))
            return
    # Compute final model parameters
    b = calc_b(X, y, w)
    if kernel_type == 'linear':
        w = calc_w(alpha, y, X)
    # Get support vectors
    alpha_idx = np.where(alpha > 0)[0]
    support_vectors = X[alpha_idx, :]
    return support_vectors, count, w, b


In [18]:
def predict(X):
    return prediction_func(X, w, b)

In [19]:
def calc_b(X, y, w):
    b_tmp = y - np.dot(w.T, X.T)
    return np.mean(b_tmp)


In [20]:
def calc_w(alpha, y, X):
    return np.dot(X.T, np.multiply(alpha,y))


In [21]:
def prediction_func(X, w, b):
    return np.sign(np.dot(w.T, X.T) + b).astype(int)


In [22]:
def prediction_error(x_k, y_k, w, b):
    return prediction_func(x_k, w, b) - y_k


In [23]:
def compute_L_H(C, alpha_prime_j, alpha_prime_i, y_j, y_i):
    if(y_i != y_j):
        return (max(0, alpha_prime_j - alpha_prime_i), min(C, C - alpha_prime_i + alpha_prime_j))
    else:
        return (max(0, alpha_prime_i + alpha_prime_j - C), min(C, alpha_prime_i + alpha_prime_j))


In [24]:
def get_rnd_int(a,b,z):
    i = z
    cnt=0
    while i == z and cnt<1000:
        i = rnd.randint(a,b)
        cnt=cnt+1
    return i
# Define kernels


In [25]:
def kernel_linear(x1, x2):
    return np.dot(x1, x2.T)


In [26]:
def kernel_quadratic(x1, x2):
    return (np.dot(x1, x2.T) ** 2)

In [27]:
kernels = {
            'linear' : kernel_linear,
            'quadratic' : kernel_quadratic
        }
# support_vectors, count, w, b = fit(np.array(X_train), np.array(y_train))
# y_pred = predict(np.array(X_test))

In [28]:
# y_test = y_test.replace(0, -1)

In [29]:
# y_test = np.array(y_test)

In [30]:
# y_test

In [31]:
# np.mean(y_test == y_pred)

In [32]:
y_pred_mat = []
for i in range (50):
#     print(y_train_df[i])
    support_vectors, count, w, b = fit(X_train, np.array(y_train_df[i]))
    y_pred = predict(X_test)
    print(y_pred)
    y_pred_mat.append(y_pred)

[-1 -1 -1 ... -1 -1 -1]
[-1 -1  1 ... -1  1  1]
[-1  1  1 ...  1  1  1]
[ 1  1 -1 ...  1  1  1]
[-1  1  1 ...  1  1  1]
[1 1 1 ... 1 1 1]
[ 1  1 -1 ...  1 -1 -1]
[-1  1  1 ...  1 -1  1]
[-1  1  1 ... -1  1 -1]
[-1 -1 -1 ... -1  1  1]
[-1 -1 -1 ... -1  1 -1]
[ 1 -1 -1 ... -1 -1 -1]
[-1  1  1 ...  1  1  1]
[ 1  1  1 ...  1  1 -1]
[-1 -1 -1 ... -1  1  1]
[-1 -1 -1 ... -1 -1  1]
[ 1  1  1 ... -1  1 -1]
[-1  1  1 ... -1  1 -1]
[1 1 1 ... 1 1 1]
[-1 -1  1 ... -1 -1 -1]
[-1  1  1 ...  1  1  1]
[-1 -1 -1 ... -1 -1 -1]
[-1 -1 -1 ... -1 -1  1]
[ 1 -1 -1 ... -1 -1 -1]
[-1 -1  1 ... -1  1  1]
[-1 -1  1 ... -1 -1  1]
[1 1 1 ... 1 1 1]
[-1 -1  1 ... -1  1  1]
[-1 -1 -1 ...  1 -1  1]
[-1 -1  1 ... -1  1 -1]
[ 1 -1 -1 ... -1 -1 -1]
[-1  1  1 ... -1  1 -1]
[-1 -1 -1 ... -1 -1 -1]
[ 1  1 -1 ... -1  1 -1]
[ 1 -1 -1 ...  1 -1 -1]
[ 1  1  1 ...  1  1 -1]
[1 1 1 ... 1 1 1]
[1 1 1 ... 1 1 1]
[ 1  1 -1 ...  1 -1  1]
[ 1  1 -1 ...  1 -1  1]
[ 1 -1 -1 ... -1  1 -1]
[ 1  1 -1 ...  1 -1  1]
[-1 -1 -1 ... -1  1 -1

In [33]:
np.array(y_train_df[0])

array([ 1,  1,  1, ...,  1,  1, -1])

In [34]:
y_pred_trans = np.array(y_pred_mat).transpose()

In [35]:
y_pred_trans

array([[-1, -1, -1, ..., -1, -1, -1],
       [-1, -1,  1, ...,  1,  1, -1],
       [-1,  1,  1, ..., -1,  1,  1],
       ...,
       [-1, -1,  1, ..., -1,  1, -1],
       [-1,  1,  1, ..., -1,  1,  1],
       [-1,  1,  1, ..., -1,  1,  1]])

In [36]:
y_pred_trans[y_pred_trans == -1] = 0

In [37]:
import csv


with open("digit_y_pred.csv","w+") as my_csv:
    csvWriter = csv.writer(my_csv,delimiter=',')
    csvWriter.writerows(y_pred_trans)

In [38]:
def hamming_distance(s1, s2):
    assert len(s1) == len(s2)
    return sum(c1 != c2 for c1, c2 in zip(s1, s2))

In [39]:
y_pred_coded = np.loadtxt(open("digit_y_pred.csv", "rb"), delimiter=",")

In [40]:
y_pred_coded.shape
y_test = np.squeeze(y_test)

In [41]:
y_pred_coded = y_pred_coded.astype(int)
x = np.array(y_test).shape[0]

In [42]:
y_pred_decoded = list()
for i in range(x):
    min_ham = np.inf
    code = 0
    temp = 0
    a = "".join(str(y_pred_coded[i]))
    for j in range (8):
        b = "".join(str(uni_code[j]))
#         print(a)
#         print(b)
        h = hamming_distance(a, b)
        if(h < min_ham):
            min_ham = h
            temp = j
    code = temp
    y_pred_decoded.append(code)

In [43]:
y_test

array([3, 2, 9, ..., 6, 7, 1])

In [44]:
np.array(y_pred_decoded)

array([6, 2, 7, ..., 6, 7, 1])

In [45]:
acc = np.mean(y_test == np.array(y_pred_decoded))

In [2]:
acc

0.85