In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8]])


In [3]:
df = pd.DataFrame(a.reshape(8,2), columns = list("xy"))

In [4]:
x = pd.get_dummies(df.x)

In [5]:
y = pd.get_dummies(df.y)

In [6]:
df = pd.concat([x,y], axis = 1)

In [7]:
df

1  2  3  4  5  6  7  8  1  2  3  4  5  6  7  8
0  1  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0
1  0  1  0  0  0  0  0  0  0  1  0  0  0  0  0  0
2  0  0  1  0  0  0  0  0  0  0  1  0  0  0  0  0
3  0  0  0  1  0  0  0  0  0  0  0  1  0  0  0  0
4  0  0  0  0  1  0  0  0  0  0  0  0  1  0  0  0
5  0  0  0  0  0  1  0  0  0  0  0  0  0  1  0  0
6  0  0  0  0  0  0  1  0  0  0  0  0  0  0  1  0
7  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  1

In [8]:
def sigmoid(z):
    return 1/(1 + np.exp(-(z)))

In [9]:
def cross_entropy(y, y_pred):
    m = y.shape[0]
    cost = -(1.0/m) * np.sum(y*np.log(y_pred) + (1-y)*np.log(1-y_pred))
    return cost

In [10]:
X = df.values[:,:8]
X

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]], dtype=uint8)

In [11]:
y

1  2  3  4  5  6  7  8
0  1  0  0  0  0  0  0  0
1  0  1  0  0  0  0  0  0
2  0  0  1  0  0  0  0  0
3  0  0  0  1  0  0  0  0
4  0  0  0  0  1  0  0  0
5  0  0  0  0  0  1  0  0
6  0  0  0  0  0  0  1  0
7  0  0  0  0  0  0  0  1

In [12]:
num_inputs = len(X[0])
num_hidden = 3
np.random.seed(4)
w1 = 2*np.random.random((num_inputs, num_hidden)) - 1
w1

array([[ 0.93405968,  0.0944645 ,  0.94536872],
       [ 0.42963199,  0.39545765, -0.56782101],
       [ 0.95254891, -0.98753949, -0.49403528],
       [-0.13041694,  0.55876584, -0.60462985],
       [ 0.72598647,  0.96680135, -0.67231552],
       [ 0.19466789, -0.9820278 , -0.22685743],
       [-0.91167988,  0.91330594, -0.12770671],
       [ 0.89795461,  0.57261197,  0.7325786 ]])

In [13]:
y = np.array(df.iloc[:, 8:])
y

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]], dtype=uint8)

In [14]:
num_outputs = len(y[0])
w2 = np.random.random((num_hidden, num_outputs)) - 1
w2

array([[-0.82683458, -0.92505141, -0.39925728, -0.83202782, -0.26661983,
        -0.59155614, -0.47209118, -0.06242842],
       [-0.47830388, -0.89180662, -0.84177659, -0.45479735, -0.47559592,
        -0.36238976, -0.59850456, -0.35019489],
       [-0.6031    , -0.37608389, -0.23259503, -0.82102609, -0.62442423,
        -0.49746694, -0.31333292, -0.74632035]])

In [19]:
y

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]], dtype=uint8)

In [15]:
alpha = 0.2 
w1_val = []
w2_val = []
for epoch in range(1000):
    z1 = np.dot(X, w1)
    a1 = sigmoid(z1)
    z2 = np.dot(a1, w2)
    a2 = sigmoid(z2)
    loss = cross_entropy(y, a2)
    a2_delta = (y - a2)*(a2 * (1-a2))
    a1_delta = a2_delta.dot(w2.T) * (a1 * (1-a1))
    w2 += a1.T.dot(a2_delta) * alpha
    w2_val.append(w2)
    w1 += X.T.dot(a1_delta) * alpha
    w1_val.append(w1)
print('Loss:', loss)

Loss: 1.5258406284644175


In [16]:
y_pred = np.argmax(a2, axis=1) 
y_result = np.argmax(y, axis = 1)
result = y_pred == np.argmax(y, axis=1)
correct = np.sum(result)/len(result)

print('Correct:',sum(result),'/',len(result))
print('Accuracy:', (correct*100),'%')

Correct: 7 / 8
Accuracy: 87.5 %


In [17]:
w2_val

[array([[-2.35571707, -1.13801077,  3.16002066, -4.22575551,  2.34107033,
         -3.05124067, -8.06679447, -0.87654193],
        [-2.33417039, -1.03711096, -6.80573383,  3.13683837, -0.99316126,
         -5.01065286,  0.34976754, -1.26474495],
        [ 0.57924958, -1.56512958, -2.29856463, -4.88048733, -7.29024517,
          2.46699674,  1.33815644, -1.60682857]]),
 array([[-2.35571707, -1.13801077,  3.16002066, -4.22575551,  2.34107033,
         -3.05124067, -8.06679447, -0.87654193],
        [-2.33417039, -1.03711096, -6.80573383,  3.13683837, -0.99316126,
         -5.01065286,  0.34976754, -1.26474495],
        [ 0.57924958, -1.56512958, -2.29856463, -4.88048733, -7.29024517,
          2.46699674,  1.33815644, -1.60682857]]),
 array([[-2.35571707, -1.13801077,  3.16002066, -4.22575551,  2.34107033,
         -3.05124067, -8.06679447, -0.87654193],
        [-2.33417039, -1.03711096, -6.80573383,  3.13683837, -0.99316126,
         -5.01065286,  0.34976754, -1.26474495],
        [ 0.